name: test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-json-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g json
      - run: json -v
